# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
    username: root
    password: test
  sql:
    init:
      data-locations: classpath:db/data-h2.sql
      schema-locations: classpath:db/schema-h2.sql
      mode: always
  h2:
    console:
      enabled: true

mybatis-plus:
  type-aliases-package: com.example.mybatisplus.entity
  configuration:
    jdbc-type-for-null: null
