spring:
  datasource:
    #H2
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
#    username: root
#    password: test

    #MySql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: Test!6266

  sql:
    init:
#      schema-locations: classpath:db/schema-h2.sql
      schema-locations: classpath:db/schema-mysql.sql
      data-locations: classpath:db/data.sql
      mode: always
#  h2:
#    console:
#      enabled: true

mybatis-plus:
  type-aliases-package: com.example.mybatisplus.entity
  configuration:
    jdbc-type-for-null: null
  global-config:
    db-config:
      logic-delete-field: deleted # 表示逻辑删除的字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  tomcat:
    accesslog:
      enabled: true
      directory: /home/justin/Sandbox/logs
      prefix: access_log_mybatisplus
